fin/dotnetfw/Dividends/Dividends/Models/Dividend.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dividends.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dividend
    {
        public int Id { get; set; }
        public string Symbol { get; set; }
        public string Name { get; set; }
        public string Sector { get; set; }
        public Nullable<double> MarketCap { get; set; }
        public Nullable<double> Beta { get; set; }
        public Nullable<double> DividendYield { get; set; }
        public Nullable<double> PERatio { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<double> DividendGrowthStreak { get; set; }
        public Nullable<double> UninterruptedDividendStreak { get; set; }
        public string PaymentFrequency { get; set; }
    }
}

fin/dotnetfw/Dividends/Dividends/Controllers/DividendsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dividends.Models;

namespace Dividends.Controllers
{
    public class DividendsController : Controller
    {
        private DividendContext db = new DividendContext();

        // GET: Dividends
        public ActionResult Index()
        {
            return View(db.Dividends.ToList());
        }

        // GET: Dividends/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dividend dividend = db.Dividends.Find(id);
            if (dividend == null)
            {
                return HttpNotFound();
            }
            return View(dividend);
        }

        //public ActionResult Details(string symbol)
        //{
        //    using (var db = new DividendContext())
        //    {
        //        var result = (from s in db.Dividends
        //                       where s.Symbol == symbol.Trim()
        //                       orderby s.Score descending
        //                       select s).FirstOrDefault();

        //        // var results = db.Dividends.Where(s => s.Symbol == symbol.Trim()).FirstOrDefault();

        //        //if (result == null)
        //        //{
        //        //    return View(new Dividend() { Symbol = $"[{symbol}] not found."});
        //        //}

        //        return View(result);
        //    }
        //}

        public ActionResult List(string name)
        {
            var result = from s in db.Dividends
                         where s.Name.Contains(name.Trim())
                         orderby s.Score descending
                         select s;

            return View(result.ToList());
        }

        public ActionResult Search(int score = 100, int streak = 0)
        {
            var result = from s in db.Dividends
                         where 
                            s.Score >= score
                            && s.UninterruptedDividendStreak >= streak
                         orderby s.Name ascending
                         select s;

            return View(result.ToList());
        }


        // GET: Dividends/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        // POST: Dividends/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Symbol,Name,Sector,MarketCap,Beta,DividendYield,PERatio,Score,DividendGrowthStreak,UninterruptedDividendStreak,PaymentFrequency")] Dividend dividend)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Dividends.Add(dividend);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(dividend);
        //}

        // GET: Dividends/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Dividend dividend = db.Dividends.Find(id);
        //    if (dividend == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(dividend);
        //}

        // POST: Dividends/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,Symbol,Name,Sector,MarketCap,Beta,DividendYield,PERatio,Score,DividendGrowthStreak,UninterruptedDividendStreak,PaymentFrequency")] Dividend dividend)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(dividend).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(dividend);
        //}

        // GET: Dividends/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Dividend dividend = db.Dividends.Find(id);
        //    if (dividend == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(dividend);
        //}

        // POST: Dividends/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Dividend dividend = db.Dividends.Find(id);
        //    db.Dividends.Remove(dividend);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

fin/dotnetfw/Dividends/Dividends/Views/Dividends/Create.cshtml
@model Dividends.Models.Dividend

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Dividend</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Symbol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Symbol, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Symbol, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sector, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sector, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sector, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MarketCap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MarketCap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MarketCap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Beta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Beta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Beta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DividendYield, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DividendYield, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DividendYield, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PERatio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PERatio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PERatio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Score, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Score, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Score, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DividendGrowthStreak, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DividendGrowthStreak, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DividendGrowthStreak, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UninterruptedDividendStreak, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UninterruptedDividendStreak, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UninterruptedDividendStreak, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentFrequency, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentFrequency, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentFrequency, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

fin/dotnetfw/Dividends/Dividends/Views/Dividends/Delete.cshtml
@model Dividends.Models.Dividend

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Dividend</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Symbol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Symbol)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sector)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sector)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MarketCap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MarketCap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Beta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Beta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DividendYield)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DividendYield)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PERatio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PERatio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DividendGrowthStreak)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DividendGrowthStreak)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UninterruptedDividendStreak)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UninterruptedDividendStreak)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentFrequency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentFrequency)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

fin/dotnetfw/Dividends/Dividends/Views/Dividends/Details.cshtml
@model Dividends.Models.Dividend

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

@using (Html.BeginForm("Details", "Dividends", FormMethod.Get))
{
    <div>
        @Html.Label("symbol", "Symbol")
    </div>
    <div>
        @Html.TextBox("symbol")
        <input type="submit" value="Submit">
    </div>
}


<div>
    <h4>Dividend</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Symbol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Symbol)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sector)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sector)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MarketCap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MarketCap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Beta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Beta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DividendYield)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DividendYield)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PERatio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PERatio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DividendGrowthStreak)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DividendGrowthStreak)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UninterruptedDividendStreak)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UninterruptedDividendStreak)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentFrequency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentFrequency)
        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

fin/dotnetfw/Dividends/Dividends/Views/Dividends/DetailsPoC.cshtml
@model Dividends.Models.Dividend

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

@using (Html.BeginForm("Details", "Dividends", FormMethod.Get))
{
    <div>
        @Html.Label("symbol", "Symbol")
    </div>
    <div>
        @Html.TextBox("symbol")
        <input type="submit" value="Submit">
    </div>
}

<div>
    <h4>Dividend</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Symbol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Symbol)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sector)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sector)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MarketCap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MarketCap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Beta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Beta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DividendYield)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DividendYield)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PERatio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PERatio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DividendGrowthStreak)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DividendGrowthStreak)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UninterruptedDividendStreak)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UninterruptedDividendStreak)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentFrequency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentFrequency)
        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

fin/dotnetfw/Dividends/Dividends/Views/Dividends/Index.cshtml
@model IEnumerable<Dividends.Models.Dividend>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
   @* @Html.ActionLink("Create New", "Create")*@
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Symbol)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sector)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MarketCap)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Beta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DividendYield)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PERatio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Score)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DividendGrowthStreak)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UninterruptedDividendStreak)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PaymentFrequency)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Symbol)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sector)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MarketCap)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Beta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DividendYield)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PERatio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Score)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DividendGrowthStreak)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UninterruptedDividendStreak)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PaymentFrequency)
        </td>
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.Id }) |*@
            @Html.ActionLink("Details", "Details", new { id=item.Id })
            @*@Html.ActionLink("Delete", "Delete", new { id=item.Id })*@
        </td>
    </tr>
}

</table>

fin/dotnetfw/Dividends/Dividends/Views/Dividends/List.cshtml
@model IEnumerable<Dividends.Models.Dividend>

@{
    ViewBag.Title = "List";
}

<h2>Search</h2>

@using (Html.BeginForm("List", "Dividends", FormMethod.Get))
{
    <div>
        @Html.Label("name", "Company Name")
    </div>
    <div>
        @Html.TextBox("name")
        <input type="submit" value="Submit">
    </div>
}

<p>

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Symbol)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sector)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MarketCap)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Beta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DividendYield)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PERatio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Score)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DividendGrowthStreak)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UninterruptedDividendStreak)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PaymentFrequency)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Symbol)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sector)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MarketCap)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Beta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DividendYield)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PERatio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Score)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DividendGrowthStreak)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UninterruptedDividendStreak)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentFrequency)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Id })
            </td>
        </tr>
    }

</table>

fin/dotnetfw/Dividends/Dividends/Views/Dividends/Search.cshtml
@model IEnumerable<Dividends.Models.Dividend>

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

@using (Html.BeginForm("Search", "Dividends", FormMethod.Get))
{
    <div style="display: table;">

        <div style="display: table-row;">
            <div style="display: table-cell; padding-right:3px">@Html.Label("score", "Score >=")</div>
            <div style="display: table-cell; padding-right:3px">@Html.Label("streak", "Uninterrupted Streak >=")</div>
        </div>

        <div style="display: table-row;">
            <div style="display: table-cell; padding-right:3px">@Html.TextBox("score")</div>
            <div style="display: table-cell; padding-right:3px">@Html.TextBox("streak")</div>
            <input type="submit" value="Submit">
        </div>

    </div>
}

<p>

</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Symbol)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sector)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MarketCap)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Beta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DividendYield)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PERatio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Score)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DividendGrowthStreak)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UninterruptedDividendStreak)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PaymentFrequency)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Symbol)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sector)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MarketCap)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Beta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DividendYield)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PERatio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Score)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DividendGrowthStreak)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UninterruptedDividendStreak)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentFrequency)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Id })
            </td>
        </tr>
    }

</table>